apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtaskys.demo.komodor.io
spec:
  group: demo.komodor.io
  names:
    kind: XTasky
    plural: xtaskys
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                image:
                  type: string
              required:
                - id
            status:
              properties:
                ns:
                  type: string
              type: object